project:
  type: website
  # resources:

website:
  title: "AMCR API"
  favicon: figs/cover.png
  repo-url: https://github.com/ARUP-CAS/aiscr-api-home/
  # repo-actions: [source, edit, issue]
  page-navigation: false
  google-analytics:
    tracking-id: "UA-79200582-4"
    anonymize-ip: true
    storage: cookies
  cookie-consent:
    type: express
    style: simple
    palette: light
  bread-crumbs: true

  navbar:
    background: dark
    search: true
    pinned: true
    logo: figs/cover_g.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "Oai-pmh Api"
        href: oai-pmh/index.qmd
    right:
      - text: "Changelogs"
        href: changelogs/index.qmd
      - text: "About"
        href: about/index.qmd

  sidebar:
    - id: main
      collapse-level: 1
      style: "floating"
      header: |
        [![](/figs/logo-amcr-hor.png)](index.qmd)
      contents:
        - index.qmd
        
    - id: oaipmh
      header: |
        [![](/figs/logo-amcr-hor.png)](/oai-pmh/index.qmd)
      contents:
        - oai-pmh/index.qmd
        
    - id: changelogs
      header: |
        [![](/figs/logo-amcr-hor.png)](/changelogs/index.qmd)
      contents:
        - auto: changelogs/
        
    - id: about
      header: |
        [![](/figs/logo-aiscr-hor.png)](/about/index.qmd)
      contents:
        - about/index.qmd

  page-footer:
    background: light
    left: |
      <a href="/about/index.qmd" class="fttext">About</a> | 
      <u id="open_preferences_center" class="fttext">Cookies</u> | 
      <span class="fttext">CC BY-NC 4.0</span>
    center: |
      <a href="https://www.aiscr.cz/" target=_blank><img src="/figs/logo-aiscr-hor.png" height="60"></a>
    right: |
      Created with &#9825; in <a href="https://www.quarto.org/" target=_blank>Quarto</a>.

format:
  html:
    toc: true
    theme:
      - spacelab
      - theme.scss
    css:
      - museo.css
    mainfont: "Alegreya Sans"
    fontsize: 1.1em
    df-print: kable
    link-external-newwindow: true
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 300px
  # pdf:
  #   documentclass: scrarticle
  #   papersize: a4wide
  #   lot: false
  #   lof: false
  # docx: default

execute:
  freeze: auto
  echo: false

crossref:
   chapters: true

callout-appearance: simple
toc-depth: 4
