---
title: "AMCR API"
format-links: false
repo-actions: false
date: 2024-08-05
doi: 10.5281/zenodo.13220182
listing: 
  - id: changelogs
    type: grid
    contents: 
      - "changelogs/20*.qmd"
    fields: [date, title, description]
    sort: "date desc"
    date-format: iso
    sort-ui: false
    categories: false
    max-items: 3
---

<!-- ::: {.callout-important}

## Webpage Under Construction

We appreciate your interest in our website. 
Please be advised that this page is currently under construction and we are working to improve your experience and will have it up and running shortly. 
Thank you for your patience and understanding. 
If you have any questions or need assistance, please [contact us](about/index.qmd).

::: -->


**Archaeological Map of the Czech Republic** (AMCR) is part of a large research infrastructure **Archaeological Information System of the Czech Republic** (AIS CR).
**AMCR API** is a homepage of AMCR application programming interfaces, currently providing data stored in the AMCR database using the *OpenArchives Initiative Protocol for Metadata Harvesting* ([OAI-PMH API](/oai-pmh/index.qmd)).

::: {.callout-note}

## Other AIS CR websites

- **AMCR homepage** is available here: [https://amcr-info.aiscr.cz](https://amcr-info.aiscr.cz){.external}.
- **Digital Archive of the AMCR**, the main interface for browsing the AMCR data, is available here: [https://digiarchiv.aiscr.cz/](https://digiarchiv.aiscr.cz/){.external}.
- Main page of **AIS CR infrastructure** is available here: [https://www.aiscr.cz/](https://www.aiscr.cz/){.external}.

:::

## API Changelog

::: {#changelogs}

:::

Older changelogs can be browsed [here](/changelogs/index.qmd).


## Licence

The data accessible through the AMCR API (and [AIS CR](https://www.aiscr.cz/){.external} in general) are published in accordance with the Open Access and with the consent of the copyright holders. 
Data usage is subject (unless explicitly stated otherwise) to the [CC BY-NC 4.0 Int. licence](https://creativecommons.org/licenses/by-nc/4.0/){.external} (*Creative Commons Attribution-NonCommercial 4.0 International*). 
Consequently, the data may only be used with proper attribution to the author/provider and exclusively for non-commercial purposes. 
This provision does not restrict the utilisation of AIS CR/AMCR data based on other contractual agreements or statutory rights. 
Use of the AMCR API for commercial purposes is permissible only upon the execution of a prior written agreement. 
If interested, please [contact us](about/index.qmd) for this purpose.

Contents of this page is licensed under the [CC BY-NC 4.0 Int.](https://creativecommons.org/licenses/by-nc/4.0/){.external} licence as well.

### Data re-use 

Because the tools managed by AIS CR provide data predominantly under *Open Access* policy, it is not possible to monitor the use of the data provided or what outputs are generated by it. 
However, as we are legally obliged to report this information, we kindly ask you as the AIS CR users to cooperate in reporting the scientific outputs that were generated using AIS CR data, tools and services.

Every AIS CR user is therefore **obliged** to:

- always indicate in the usual way in specific outputs that the AIS CR infrastructure has been used to produce them, referring to the data or tool used;
- when entering output information into the [Results Information Register -- RIV](https://www.isvavai.cz/riv){.external} (e.g. at the institutes of the [Czech Academy of Sciences](https://www.avcr.cz/){.external} sites via the [ASEP database](https://asep.lib.cas.cz/){.external}), select the proper link of the result to the AIS CR infrastructure in the field of LRI (Large Research Infrastructures) from the offered project code list of large research infrastructures;
- kindly let us know via this [questionnaire](https://www.aiscr.cz/vystupy){.external} that the output has been published.


## Citation

Please cite the use of the data queried from the API in scientific publications as follows:

> AMCR: *Archaeological Map of the Czech Republic.* [cit. YYYY-MM-DD]. Available from: [https://api.aiscr.cz/](https://api.aiscr.cz/)

And the API documentation as:

> Pajdla P., Novák D. 2024: AMCR API Documentation. DOI: [10.5281/zenodo.13220182](https://zenodo.org/doi/10.5281/zenodo.13220182). Website: [https://arup-cas.github.io/aiscr-api-home/](https://arup-cas.github.io/aiscr-api-home/). Source: [https://github.com/ARUP-CAS/aiscr-api-home](https://github.com/ARUP-CAS/aiscr-api-home).
